import fs from "node:fs/promises";

type VL = {
  version: string;
  license: string;
};
async function $getLocalPackage(): Promise<VL> {
  const _data = JSON.parse(await fs.readFile("package.json", "utf8"));
  return {
    version: _data.version,
    license: _data.license,
  };
}
export const { version, license } = await $getLocalPackage();

const nyeinBannerText = `// generated by nyein v${version} , ${license}`;

export default nyeinBannerText;
