import fs from "node:fs/promises";
async function $getLocalPackage() {
  const _data = JSON.parse(await fs.readFile("package.json", "utf8"));
  return {
    version: _data.version,
    license: _data.license,
  };
}
const { version, license } = await $getLocalPackage();

const nyeinBannerText = `// generated by nyein v${version} , ${license}`;

export default nyeinBannerText;
